fix: don't throw error when lib.name is null (#104)
Fixes https://github.com/GregoryConrad/native_toolchain_rust/issues/103

I can't reproduce the error in the unit tests, but it does fix it in my
real app:
```console
Building Linux application...
✓ Built build/linux/x64/release/bundle/saber
ahann@dellpro:~/Documents/GitHub/saber$ flutter build linux # without this patch
ERROR: [SEVERE] RustBuilder: Failed to find lib.name in /home/ahann/.pub-cache/hosted/pub.dev/super_native_extensions-0.10.0-dev.2/rust/Cargo.toml: [workspace]
ERROR: [SEVERE] RustBuilder: Failed to find lib.name in /home/ahann/.pub-cache/hosted/pub.dev/super_native_extensions-0.10.0-dev.2/rust/Cargo.toml: [workspace]
Building Linux application...                                           
✓ Built build/linux/x64/release/bundle/saber
ahann@dellpro:~/Documents/GitHub/saber$ flutter build linux # with this patch
Building Linux application...                                           
✓ Built build/linux/x64/release/bundle/saber
ahann@dellpro:~/Documents/GitHub/saber$ 
```